name: Deploy U-Net API to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to VM via SSH
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER_NAME: ${{ secrets.EC2_USER }}
        run: |
          # 1. Préparation de la clé SSH
          printf "%s" "$PRIVATE_KEY" > private_key
          chmod 600 private_key

          # 2. Exécution des commandes sur la VM
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOST} << 'EOF'
            echo "--- Connexion établie avec succès ---"
            
            # Charger Conda proprement pour le shell non-interactif
            source ~/miniconda3/etc/profile.d/conda.sh
            
            # 3. Gestion du dossier et Git LFS
            if [ ! -d "unet_api" ]; then
              git clone https://github.com/NetZach777/unet_api.git unet_api
              cd unet_api
              git lfs install
            else
              cd unet_api
              git reset --hard HEAD
              git pull origin main
            fi
            
            # Télécharger les fichiers volumineux (le modèle .h5)
            git lfs pull

            # 4. Activation de l'environnement
            # On part du principe que tu l'as déjà créé manuellement comme on a vu
            conda activate unet_api_env

            # 5. Installation des dépendances
            # Utilisation de --no-cache-dir pour économiser la RAM
            pip install --no-cache-dir -r requirements.txt

            # 6. Relance du serveur FastAPI
            echo "Nettoyage du port 8000..."
            sudo fuser -k 8000/tcp || true
            
            echo "Lancement d'Uvicorn..."
            # On utilise 'python -m uvicorn' pour être certain d'utiliser celui de l'env conda
            nohup python -m uvicorn main:app --host 0.0.0.0 --port 8000 > uvicorn.log 2>&1 &
            
            echo "--- Déploiement terminé ! ---"
          EOF

          # 7. Nettoyage
          rm private_key
